### ISSUE TITLE
No Servers Configured

### ISSUE THREAD

**Issue by Tsolete** [SwaroopGiri/Pihole-with-Anonymized-ODOH#1]
Hi. I've followe your guide to configure DNSCrypt on my Pi Hole but when y execute the command sudo "./dnscrypt-proxy"  gives me a  fatal error "no servers configured". I've tried some things with no luck. Any ideas? I also attach my dnscrypt-proxy.toml
[dnscrypt-proxy.txt](https://github.com/SwaroopGiri/Pihole-with-Anonymized-ODOH/files/8358378/dnscrypt-proxy.txt)

**Comment by SwaroopGiri** [comment]
Took a quick look at your file and it's probably because you've used incorrect servers and relay combination. try adding or changing servers/relays to check if it works. You can find the list [here](https://github.com/dnscrypt/dnscrypt-resolvers)

**Comment by Tsolete** [comment]
I've just tried to put the same servers as you, and it gives me same error. Here's the updated .toml file. Maybe I'm missing something but I'm unable to find it.
[dnscrypt-proxy.txt](https://github.com/SwaroopGiri/Pihole-with-Anonymized-ODOH/files/8360371/dnscrypt-proxy.txt)

**Comment by SwaroopGiri** [comment]
You have odoh relays but no odoh servers configured in [sources] section. Try comparing your toml file with (https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml). Check and uncomment odoh servers under [sources]

If that doesn't work, I'd recommend you to start editing a fresh example file from scratch and giving it another shot.

**Comment by Tsolete** [comment]
Thank you very much. Problem solved. I was missing the Odoh servers. I was misunderstanding the instructions. Thanks again.
