### ISSUE TITLE
[FATAL] toml: type mismatch for main.StaticConfig: expected table but found []interface {}

### ISSUE THREAD

**Issue by DawsonD43** [SwaroopGiri/Pihole-with-Anonymized-ODOH#3]
When trying to install and start the service after configuring the .toml file, I am receiving the error in the title. I put these lines at the very bottom of the file per the documentation (I have been following the documentation and using the example servers and relays.)

```
[static]
routes = [
     { server_name='odoh-cloudflare', via=['odohrelay-crypto-sx', 'odohrelay-surf'] },
     { server_name='odohrelay-koki-ams', via=['odohrelay-koki-ams', 'odohrelay-koki-bcn'] }
]
```

**Comment by SwaroopGiri** [comment]
You don't need to add a static entry at the very end of toml file. You just need to uncomment below part under `Anonymized DNS` section of the file and edit servers in it.
```
# routes = [
#    { server_name='example-server-1', via=['anon-example-1', 'anon-example-2'] },
#    { server_name='example-server-2', via=['sdns://gRIxMzcuNzQuMjIzLjIzNDo0NDM'] }
# ]
```
